Port to POSIX sh

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -1,6 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
-VERSION="1.2.3"
+VERSION="2.0.0"
 DIR_CONFIG="$HOME/.pushover"
 
 USER=""
@@ -17,295 +17,267 @@ TIMESTAMP=""
 PRIORITY="0"
 RETRY="60"
 EXPIRE="3600"
+VERBOSE=""
 
 config() {
-	LABEL_USER_KEY="User Key"
-	LABEL_APP_TOKEN="API Token"
-	echo -ne '\033[0;37m\n'
-	if [ -n "${CONFIG}" ] && [ ${CONFIG} == "rm" ]; then
-		rm -rf ${DIR_CONFIG}
-		echo -ne "Pushover CLI configuration deleted.\n\n"
-		echo -ne '\033[0m'
-		exit 0
-	fi
-	if [ -e ${DIR_CONFIG}/config ]; then
-	    USER_KEY=$(awk -F'"' '/^USER_KEY=/ {print $2}' ${DIR_CONFIG}/config)
-	    APP_TOKEN=$(awk -F'"' '/^APP_TOKEN=/ {print $2}' ${DIR_CONFIG}/config)
-	    if [ -z "${USER_KEY}" ]; then echo -ne "${LABEL_USER_KEY}: "; else echo -ne "${LABEL_USER_KEY} [****************${USER_KEY: -4}]: "; fi
-	    read USER_KEY
-	    if [ -z "${APP_TOKEN}" ]; then echo -ne "${LABEL_APP_TOKEN}: "; else echo -ne "${LABEL_APP_TOKEN} [****************${APP_TOKEN: -4}]: "; fi
-	    read APP_TOKEN
-	else
-		echo -ne "${LABEL_USER_KEY}: "
-		read USER_KEY
-		echo -ne "${LABEL_APP_TOKEN}: "
-		read APP_TOKEN
-		if [ ! -d ${DIR_CONFIG} ]; then mkdir ${DIR_CONFIG}; fi
-		if [ -e ${DIR_CONFIG}/config ]; then touch ${DIR_CONFIG}/config; fi
-	fi
-	cat <<EOF > ${DIR_CONFIG}/config
+    LABEL_USER_KEY="User Key"
+    LABEL_APP_TOKEN="API Token"
+    if [ -n "${CONFIG}" ] && [ "${CONFIG}" = "rm" ]; then
+        rm -rf "${DIR_CONFIG}"
+        echo "Pushover CLI configuration deleted."
+        exit 0
+    fi
+    [ -d "${DIR_CONFIG}" ] || mkdir -m 700 "${DIR_CONFIG}"
+    if [ ! -e "${DIR_CONFIG}"/config ]; then
+        touch "${DIR_CONFIG}"/config
+    else
+        USER_KEY=$(awk -F'"' '/^USER_KEY=/ {print $2}' "${DIR_CONFIG}"/config)
+        APP_TOKEN=$(awk -F'"' '/^APP_TOKEN=/ {print $2}' "${DIR_CONFIG}"/config)
+    fi
+
+    printf '%s' "$LABEL_USER_KEY"
+    if [ -n "${USER_KEY}" ]; then
+        printf ' [****************%s]' "$(printf '%s' "$USER_KEY" | rev | cut -c 1-4 | rev)"
+    fi
+    printf ': '
+    read -r USER_KEY
+    
+    printf '%s' "$LABEL_APP_TOKEN"
+    if [ -n "$APP_TOKEN" ]; then
+        printf ' [****************%s]' "$(printf '%s' "$APP_TOKEN" | rev | cut -c 1-4 | rev)"
+    fi
+    printf ': '
+    read -r APP_TOKEN
+    cat <<EOF > "${DIR_CONFIG}"/config
 USER_KEY="${USER_KEY}"
 APP_TOKEN="${APP_TOKEN}"
 EOF
-	chmod 600 ${DIR_CONFIG}/config
-	echo -ne "\nPushover CLI configured successfully.\n\n"
-	echo -ne '\033[0m'
-}
-upgrade() {
-	DIR_TEMP="/tmp/pushover-cli"
-	DIR_BIN="/usr/local/bin"
-	BRANCH="${UPGRADE}"
-	if [ "${BRANCH}" == "dev" ]; then BRANCH="develop"; else BRANCH="master"; fi
-	echo -ne '\033[0;37m'
-	echo -ne "\nDownloading latest version..."
-	curl -s https://raw.githubusercontent.com/aaronfagan/pushover-cli/${BRANCH}/install.sh | bash -s ${BRANCH} upgrade > /dev/null 2>&1
-	if [ $? == 0 ]; then
-		echo -ne "done!"
-		VERSION_OLD=${VERSION}
-		VERSION_NEW=$(awk -F'"' '/^VERSION=/ {print $2}' ${DIR_TEMP}/pushover)
-		if [ "${VERSION_OLD}" == "${VERSION_NEW}" ]; then
-			echo -ne "\nPushover CLI is already the latest version (v${VERSION_OLD}).\n\n"
-		else
-			echo -ne "\nPushover CLI upgraded successfully (v${VERSION_OLD} => v${VERSION_NEW}).\n\n"
-		fi
-		echo -ne '\033[0m'
-		rm -rf ${DIR_TEMP}
-		exit 0
-	else
-		echo -ne "failed!"
-		echo -ne "\nPushover CLI upgrade failed.\n\n"
-		echo -ne '\033[0m'
-		rm -rf ${DIR_TEMP}
-		exit 1
-	fi
+    chmod 600 "${DIR_CONFIG}"/config
+    echo "Pushover CLI configured successfully."
 }
 version() {
-	echo -ne "\033[0;37m
-Pushover CLI - v${VERSION} - https://github.com/aaronfagan/pushover-cli/
-By Aaron Fagan - https://www.aaronfagan.ca/
-\033[0m\n"
+    echo "Pushover CLI version ${VERSION}"
 }
 usage() {
-	echo "
+    cat <<EOF
+Pushover CLI is a tool to send Pushover notifications from the command line
+
 Usage:
-	pushover [options]
+  pushover [options]
+
 Options:
-	--user          Pushover user key. REQUIRED.
-	--token         Pushover application API token. REQUIRED.
-	--title         Notification title.
-	--message       Notification message. If you are seeing errors, try wrapping your message in 'single quotes.' REQUIRED.
-	--url           A supplementary URL to show with your message.
-	--url-title     A title for your supplementary URL, otherwise just the URL is shown.
-	--device        The target device(s) to send the notification to. Comma separated, no spaces. DEFAULT = All devices.
-	--sound	        The notification sound to play upon delivery. More Info: https://pushover.net/api#sounds
-	--html          Enabled HTML message. Set to 1 to enable. More Info: https://pushover.net/api#html
-	--monospace     Enabled Monospace message. Set to 1 to enable. May not be used if --html is used, and vice versa.
-	--timestamp     A Unix timestamp of your message's date and time to display to the user. DEFAULT = The time your message is received by the Pushover API.
-	--priority      Message priority. More Info: https://pushover.net/api#priority. DEFAULT = $PRIORITY.
-	--retry         How many seconds between retries. Only applies when --priority is set to 2 (emergency). DEFAULT = $RETRY.
-	--expire        How many seconds until emergency notification retries will stop. Only applies when --priority is set to 2 (emergency). DEFAULT = $EXPIRE.
-	--config        Configure global Pushover user key and application API token. Set to 'rm' to delete configuration files.
-	--upgrade       Upgrade to the latest Pushover CLI version.'.
-	--version, -v   Currently installed version of Pushover CLI.
-	--quiet, -q     Silence all output.
-	--help          Usage instructions.
+  -u, --user        Pushover user key. REQUIRED.
+  -a, --token       Pushover application API token. REQUIRED.
+  -t, --title       Notification title.
+  -m, --message     Notification message. If you are seeing errors, try wrapping your message in 'single quotes.' REQUIRED.
+      --url         A supplementary URL to show with your message.
+      --url-title   A title for your supplementary URL, otherwise just the URL is shown.
+  -d, --device      The target device(s) to send the notification to. Comma separated, no spaces. DEFAULT = All devices.
+  -s, --sound       The notification sound to play upon delivery. More Info: https://pushover.net/api#sounds
+      --html        Enabled HTML message. Set to 1 to enable. More Info: https://pushover.net/api#html
+      --monospace   Enabled Monospace message. Set to 1 to enable. May not be used if --html is used, and vice versa.
+      --timestamp   A Unix timestamp of your message's date and time to display to the user. DEFAULT = The time your message is received by the Pushover API.
+  -p, --priority    Message priority. More Info: https://pushover.net/api#priority. DEFAULT = $PRIORITY.
+  -r, --retry       How many seconds between retries. Only applies when --priority is set to 2 (emergency). DEFAULT = $RETRY.
+  -e, --expire      How many seconds until emergency notification retries will stop. Only applies when --priority is set to 2 (emergency). DEFAULT = $EXPIRE.
+  -c, --config      Configure global Pushover user key and application API token. Set to 'rm' to delete configuration files.
+  -V, --version     Currently installed version of Pushover CLI.
+  -v, --verbose     Enable verbose output.
+  -q, --quiet       Silence all output.
+  -h, --help        Usage instructions.
+
 Example:
-	pushover \\
-	--user YOUR_USER_KEY \\
-	--token YOUR_APP_TOKEN \\
-	--title \"Test Notification\" \\
-	--message \"Here is the notification!\"
-	"
+  pushover \\
+  --user YOUR_USER_KEY \\
+  --token YOUR_APP_TOKEN \\
+  --title "Test Notification" \\
+  --message "Here is the notification!"
+EOF
 }
 
-while [[ $# -gt 0 ]]; do
-	key="$1"
-	case $key in
-		--token)
-			TOKEN="${2:-${TOKEN}}"
-			shift
-			shift
-		;;
-		--user)
-			USER="${2:-${USER}}"
-			shift
-			shift
-		;;
-		--title)
-			TITLE="${2:-$TITLE}"
-			shift
-			shift
-		;;
-		--message)
-			MESSAGE="${2:-${MESSAGE}}"
-			shift
-			shift
-		;;
-		--url)
-			URL="${2:-$URL}"
-			shift
-			shift
-		;;
-		--url-title)
-			URL_TITLE="${2:-$URL_TITLE}"
-			shift
-			shift
-		;;
-		--device)
-			DEVICE="${2:-$DEVICE}"
-			shift
-			shift
-		;;
-		--sound)
-			SOUND="${2:-$SOUND}"
-			shift
-			shift
-		;;
-		--html)
-			HTML="${2:-$HTML}"
-			shift
-			shift
-		;;
-		--monospace)
-			MONOSPACE="${2:-$MONOSPACE}"
-			shift
-			shift
-		;;
-		--timestamp)
-			TIMESTAMP="${2:-$TIMESTAMP}"
-			shift
-			shift
-		;;
-		--priority)
-			PRIORITY="${2:-$PRIORITY}"
-			shift
-			shift
-		;;
-		--retry)
-			RETRY="${2:-$RETRY}"
-			shift
-			shift
-		;;
-		--expire)
-			EXPIRE="${2:-$EXPIRE}"
-			shift
-			shift
-		;;
-		--config)
-			CONFIG="${2:-$CONFIG}"
-			shift
-			shift
-			config
-			exit 0
-		;;
-		--upgrade)
-			UPGRADE="${2:-$UPGRADE}"
-			shift
-			shift
-			upgrade
-		;;
-		-v | --version)
-			shift
-			version
-			exit 0
-		;;
-		-q | --quiet)
-			shift
-			QUIET=TRUE
-		;;
-		--help)
-			shift
-			usage
-			exit 0
-		;;
-		*) 
-			INVALID+=("$1")
-			shift
-			echo -ne "\033[0;31m\nERROR:\033[0;37m Invalid arguement: ${INVALID}\033[0m\n"
-			usage
-			exit 1
-		;;
-	esac
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -a | --token)
+            TOKEN="${2:-${TOKEN}}"
+            [ -z "$2" ] || shift
+        ;;
+        -u | --user)
+            USER="${2:-${USER}}"
+            [ -z "$2" ] || shift
+        ;;
+        -t | --title)
+            TITLE="${2:-$TITLE}"
+            [ -z "$2" ] || shift
+        ;;
+        -m | --message)
+            MESSAGE="${2:-${MESSAGE}}"
+            [ -z "$2" ] || shift
+        ;;
+        --url)
+            URL="${2:-$URL}"
+            [ -z "$2" ] || shift
+        ;;
+        --url-title)
+            URL_TITLE="${2:-$URL_TITLE}"
+            [ -z "$2" ] || shift
+        ;;
+        -d | --device)
+            DEVICE="${2:-$DEVICE}"
+            [ -z "$2" ] || shift
+        ;;
+        -s | --sound)
+            SOUND="${2:-$SOUND}"
+            [ -z "$2" ] || shift
+        ;;
+        --html)
+            HTML="${2:-$HTML}"
+            [ -z "$2" ] || shift
+        ;;
+        --monospace)
+            MONOSPACE="${2:-$MONOSPACE}"
+            [ -z "$2" ] || shift
+        ;;
+        --timestamp)
+            TIMESTAMP="${2:-$TIMESTAMP}"
+            [ -z "$2" ] || shift
+        ;;
+        -p | --priority)
+            PRIORITY="${2:-$PRIORITY}"
+            [ -z "$2" ] || shift
+        ;;
+        -r | --retry)
+            RETRY="${2:-$RETRY}"
+            [ -z "$2" ] || shift
+        ;;
+        -e | --expire)
+            EXPIRE="${2:-$EXPIRE}"
+            [ -z "$2" ] || shift
+        ;;
+        -c | --config)
+            CONFIG="${2:-$CONFIG}"
+            [ -z "$2" ] || shift
+            config
+            exit 0
+        ;;
+        -V | --version)
+            version
+            exit 0
+        ;;
+        -v | --verbose)
+            VERBOSE=true
+        ;;
+        -q | --quiet)
+            QUIET=true
+        ;;
+        -h | --help)
+            usage
+            exit 0
+        ;;
+        *)
+            printf 'Invalid argument: %s' "$1"
+            usage
+            exit 1
+        ;;
+    esac
+
+    shift 1
 done
 
 if [ -z "${USER}" ] || [ -z "${TOKEN}" ] || [ -z "${MESSAGE}" ]; then
-	if [ -z "${QUIET}" ]; then
-		echo -ne '\n'
-	fi
-	if [ -z "${USER}" ]; then 
-		if [ -e ${DIR_CONFIG}/config ]; then
-		    USER=$(awk -F'"' '/^USER_KEY=/ {print $2}' ${DIR_CONFIG}/config)
-		    if [ -z "${USER}" ]; then
-		    	if [ -z "${QUIET}" ]; then
-		    		echo -ne "\033[0;31mERROR:\033[0;37m --user arguement is required.\033[0m\n"
-		    	fi
-		    fi
-		else
-			if [ -z "${QUIET}" ]; then
-				echo -ne "\033[0;31mERROR:\033[0;37m --user arguement is required.\033[0m\n"
-			fi
-		fi
-	fi
-	if [ -z "${TOKEN}" ]; then
-		if [ -e ${DIR_CONFIG}/config ]; then
-		    TOKEN=$(awk -F'"' '/^APP_TOKEN=/ {print $2}' ${DIR_CONFIG}/config)
-		    if [ -z "${TOKEN}" ]; then
-		    	if [ -z "${QUIET}" ]; then
-		    		echo -ne "\033[0;31mERROR:\033[0;37m --token arguement is required.\033[0m\n"
-		    	fi
-		    fi
-		else
-			if [ -z "${QUIET}" ]; then
-				echo -ne "\033[0;31mERROR:\033[0;37m --token arguement is required.\033[0m\n"
-			fi
-		fi
-	fi
-	if [ -z "${MESSAGE}" ]; then
-		if [ -z "${QUIET}" ]; then
-			echo -ne "\033[0;31mERROR:\033[0;37m --message arguement is required.\033[0m\n"
-		fi
-	fi
+    if [ -z "${USER}" ]; then 
+        if [ -e "${DIR_CONFIG}"/config ]; then
+            USER=$(awk -F'"' '/^USER_KEY=/ {print $2}' "${DIR_CONFIG}"/config)
+            if [ -z "${USER}" ]; then
+                if [ -z "${QUIET}" ]; then
+                    echo "--user argument is required." >&2
+                fi
+            fi
+        else
+            if [ -z "${QUIET}" ]; then
+                echo "--user argument is required." >&2
+            fi
+        fi
+    fi
+    if [ -z "${TOKEN}" ]; then
+        if [ -e "${DIR_CONFIG}"/config ]; then
+            TOKEN=$(awk -F'"' '/^APP_TOKEN=/ {print $2}' "${DIR_CONFIG}"/config)
+            if [ -z "${TOKEN}" ]; then
+                if [ -z "${QUIET}" ]; then
+                    echo "--token argument is required." >&2
+                fi
+            fi
+        else
+            if [ -z "${QUIET}" ]; then
+                echo "--token argument is required." >&2
+            fi
+        fi
+    fi
+    if [ -z "${MESSAGE}" ]; then
+        if [ -z "${QUIET}" ]; then
+            echo "--message argument is required." >&2
+        fi
+    fi
 fi
 
 if [ -z "${USER}" ] || [ -z "${TOKEN}" ] || [ -z "${MESSAGE}" ]; then
-	if [ -z "${QUIET}" ]; then
-		usage
-	fi
-	exit 1
+    if [ -z "${QUIET}" ]; then
+        usage
+    fi
+    exit 1
 else
-	if [ -z "${QUIET}" ]; then
-		echo -ne '\033[0;37m'
-		echo -ne "> Sending notification..."
-	fi
-	CURL=$(/usr/bin/curl -s \
-		-F "token=${TOKEN}" \
-		-F "user=${USER}" \
-		-F "title=${TITLE}" \
-		-F "message=$(echo -e ${MESSAGE})" \
-		-F "url=${URL}" \
-		-F "url_title=${URL_TITLE}" \
-		-F "device=${DEVICE}" \
-		-F "sound=${SOUND}" \
-		-F "html=${HTML}" \
-		-F "monospace=${MONOSPACE}" \
-		-F "timestamp=${TIMESTAMP}" \
-		-F "priority=${PRIORITY}" \
-		-F "retry=${RETRY}" \
-		-F "expire=${EXPIRE}" \
-		https://api.pushover.net/1/messages.json)
-	ERROR=$(echo ${CURL} | grep 'errors')
-	if [ -z "${ERROR}" ]; then
-		if [ -z "${QUIET}" ]; then
-			echo -ne "success!\n\n";
-			echo -ne '\033[0m'
-		fi
-		exit 0
-	else
-		if [ -z "${QUIET}" ]; then
-			echo -ne "failed!\n\n";
-			echo -ne "\033[0;31mERROR:\033[0;37m ${ERROR}.\033[0m\n\n"
-			echo -ne '\033[0m'
-		fi
-		exit 1;
-	fi
+    set -- curl -s -X POST -F "token=${TOKEN}" -F "user=${USER}" -F "message=${MESSAGE}"
+    if [ -n "${TITLE}" ]; then
+        set -- "${@}" -F "title=${TITLE}"
+    fi
+    if [ -n "${URL}" ]; then
+        set -- "${@}" -F "url=${URL}"
+    fi
+    if [ -n "${URL_TITLE}" ]; then
+        set -- "${@}" -F "url_title=${URL_TITLE}"
+    fi
+    if [ -n "${DEVICE}" ]; then
+        set -- "${@}" -F "device=${DEVICE}"
+    fi
+    if [ -n "${SOUND}" ]; then
+        set -- "${@}" -F "sound=${SOUND}"
+    fi
+    if [ -n "${HTML}" ]; then
+        set -- "${@}" -F "html=${HTML}"
+    fi
+    if [ -n "${MONOSPACE}" ]; then
+        set -- "${@}" -F "monospace=${MONOSPACE}"
+    fi
+    if [ -n "${TIMESTAMP}" ]; then
+        set -- "${@}" -F "timestamp=${TIMESTAMP}"
+    fi
+    if [ -n "${PRIORITY}" ]; then
+        set -- "${@}" -F "priority=${PRIORITY}"
+    fi
+    if [ -n "${RETRY}" ]; then
+        set -- "${@}" -F "retry=${RETRY}"
+    fi
+    if [ -n "${EXPIRE}" ]; then
+        set -- "${@}" -F "expire=${EXPIRE}"
+    fi
+
+    set -- "${@}" https://api.pushover.net/1/messages.xml
+
+    [ -z "${VERBOSE}" ] || echo "${@}"
+
+    if [ -z "${QUIET}" ]; then
+        printf 'Sending notification... '
+    fi
+
+    RESULT=$("${@}")
+    if echo "$RESULT" | grep -q errors; then
+        if [ -z "${QUIET}" ]; then
+            printf 'failed: %s\n' "$(echo "$RESULT" | grep -oP '<error>.*?</error>' | sed 's/<[^>]*>//g')"
+        fi
+        exit 1
+    else
+        if [ -z "${QUIET}" ]; then
+            echo success
+        fi
+        exit 0
+    fi
 fi
